wms_index:
    pattern: /
    defaults: {_controller: "MBWMSBundle:WMS:index"}
    requirements:
        _method: GET

wms_details:
    pattern: /{wmsId}
    defaults: { _controller: "MBWMSBundle:WMS:details"}
    requirements:
        wmsId: \d+
        _method: GET

wms_showadd:
    pattern: /add
    defaults: { _controller: "MBWMSBundle:WMS:showadd"}
    requirements:
        _method: GET

wms_add:
    pattern: /
    defaults: { _controller: "MBWMSBundle:WMS:add"}
    requirements:
        _method: POST

wms_preview:
    pattern: /preview
    defaults: { _controller: "MBWMSBundle:WMS:preview"}
    requirements:
        _method: POST

wms_showdelete:
    pattern: /{wmsId}/DELETE
    defaults: {_controller: "MBWMSBundle:WMS:showdelete" }
    requirements:
        wmsId: \d+
        _method: GET

wms_delete:
    pattern: /{wmsId}/DELETE
    defaults: {_controller: "MBWMSBundle:WMS:showdelete" }
    requirements:
        wmsId: \d+
        _method: POST
