language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
before_script:
  - cd ..
  - git clone https://github.com/mapbender/mapbender-starter
  - cd mapbender-starter
  - git checkout feature/testing
  - git checkout $TRAVIS_BRANCH
  - git submodule update --init --recursive
  - cd application
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer update --dev
  - rm -rf mapbender
  - ln -s ../../mapbender
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
  - php app/console fom:user:resetroot --username root --password root --email root@root.de --silent
  - phantomjs --webdriver=9876 &
  - export PJSPORT=$(echo $!)
  - pip install selenium
script: phpunit -c app/ --coverage-clover ../testresults/clover.xml
after_script:
  - php bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - cd mapbender
  - export MYREV=$(git rev-parse HEAD)
  - cd ..
  - cat /tmp/weblog
  - php ocular.phar code-coverage:upload --repository g/mapbender/mapbender --format=php-clover ../testresults/clover.xml --revision $MYREV
  - kill -9 $PJSPORT
