language: php
env:
  global:
    - secure: "R/frivP2njTayUQqNfgCZT06dfeyVFeDcRP4O+ImBTbTdpqoXBu8CmEqBbeNuk9bje1i4W1GWTX8WEAwpxHeNEDubsCScxc4PFNKqDU9TIU8nVAE5gwgrSiigJk7LlnQfkHNzFngak0godcAUas27DG7tFRWPA7VNbKJ3pJumf4="
    - secure: "T5FALrFEEcaeLQVPgdULZ2jvv3VRrhcvX0vWVzfV1OHUttYx5TXPyJRHv60eZecWUtO/HjzkaQeDxsfcrYOD5s9tuFeruw5gXxhDDn0ZM5Jcv7K9YGqCQ7IoOI+qgWZZuntEOhwzTHAAfsfEpf7nqKwJ5CJFicJDV0sIOIvN480="

php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - cd ..
  - git clone https://github.com/mapbender/mapbender-starter
  - cd mapbender-starter
  - git checkout feature/testing
  - git submodule update --init --recursive
  - cd application
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer update --dev
  - rm -rf mapbender
  - ln -s ../../mapbender
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
  - php app/console fom:user:resetroot --username root --password root --email root@root.de --silent
  - phantomjs --webdriver=9876 &
  - export PJSPORT=$(echo $!)
script: phpunit -c app/ --coverage-clover ../testresults/clover.xml
after_script:
  - php bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - cd mapbender
  - export MYREV=$(git rev-parse HEAD)
  - cd ..
  - cat /tmp/weblog
  - php ocular.phar code-coverage:upload --repository g/mapbender/mapbender --format=php-clover ../testresults/clover.xml --revision $MYREV
  - kill -9 $PJSPORT
